<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1CCS179" failures="1" tests="4" name="Test" time="85.943" errors="0" timestamp="2023-02-10T21:13:16 IST">
  <testcase classname="demo.TestCase" name="verifyLoginWithCorrectCred" time="6.008"/>
  <testcase classname="demo.TestCase" name="verifyLoginWithCorrectCred" time="11.609"/>
  <testcase classname="demo.TestCase" name="verifyLoginWithCorrectCred" time="5.841"/>
  <testcase classname="demo.TestCase" name="verifyLoginWithCorrectCred" time="5.749">
    <failure type="java.lang.AssertionError" message="expected [https://www.apps.dalalstreet.ai/dashboard] but found [https://www.apps.dalalstreet.ai/login]">
      <![CDATA[java.lang.AssertionError: expected [https://www.apps.dalalstreet.ai/dashboard] but found [https://www.apps.dalalstreet.ai/login]
at demo.TestCase.verifyLoginWithCorrectCred(TestCase.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithCorrectCred -->
</testsuite> <!-- Test -->
